version: '3'

services:
#  sf-chat-service:
#    build:
#      context: ./sf-chat-service
#    ports:
#      - "8080:8080"
#    expose:
#      - "8080"
#    networks:
#      - backend

  service-discovery:
    build:
      context: ./sf-service-discovery
    ports:
      - "8761:8761"
    expose:
      - "8761"
    networks:
      - backend

  mongodb:
    image: mongo:latest
#    image: bitnami/mongodb:latest
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    expose:
      - "27017"
    networks:
      - backend

#  mongo-express:
#    image: mongo-express:latest
#    restart: always
#    ports:
#      - "8082:8081"
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: password
#    depends_on:
#      - mongo

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mongodata: