spring:
  application:
    name: sf-chat-service
  data:
    mongodb:
      uri: mongodb://localhost/sf-chat-service
      host: localhost
      port: 27017
      database: sf-chat-service
      auto-index-creation: true
      uuid-representation: standard
  rsocket:
    server:
      transport: websocket
      port: 9090
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/sf-chat

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/